const Images = {
    RaagaNewLogo:require('../assets/raaga_new_logo.png'),
    NoInternet:require('../assets/noInternet.png'),
    Login: require('../assets/login_image.jpg'),
    Shampoo: require('../assets/shampoo.png'),
    LogoNew: require('../assets/raaga_new_logo.png'),
    FeedBack:require('../assets/feedback.gif'),
    Location: require('../assets/location.gif'),
    TheoryPopUp: require('../assets/red.gif'),
    Person:require('../assets/person.png'),
    Share:require('../assets/share.png'),
    Receipt:require('../assets/receipt.png'),
    LocationGrey:require('../assets/location_grey.png'),
    Gps: require('../assets/gps.png'),
    TheoryImg:require('../assets/theory_img.png'),
    PaperClip:require('../assets/paperclip.png'),
    Info:require('../assets/info.png'),
    Gallery:require('../assets/gallery.png'),
    Navigation:require('../assets/navigation.png'),
    ReinviteStart:require('../assets/reinvite-start.png'),
    Maximize:require('../assets/maximize.png'),
    ClientImg:require('../assets/client_img.png'),
    TickSquare:require('../assets/tick-square.png'),
    Sun:require('../assets/sun.png'),
    Timer:  require('../assets/timer.png'),
    AcceptTick:require('../assets/accept-tick.png'),
    AddSquare:require('../assets/add-square.png'),
    ArrowSquareRight:require('../assets/arrow-square-right.png'),
    Flag2:require('../assets/flag-2.png'),
    BackgroundPattern:require('../assets/background-pattern.png'),
    CalendarBlueNew:require('../assets/calendar_blue_new.png'),
    Logout:require('../assets/logout.png'),
    RightArrow:require('../assets/right_arrow.png'),
    DemoClock:require('../assets/demoClock.png'),
    Setting:require('../assets/setting.png'),
    BoxTime:require('../assets/box-time.png'),
    PeopleNew:require('../assets/people_new.png'),
    Note:require('../assets/note.png'),
    SendSqaure:require('../assets/send-sqaure.png'),
    Cat:require('../assets/cat.gif'),
    CalendarEditNew:require('../assets/calendar_edit_new.png'),
    Search:require('../assets/search.png'),
    Clock:require('../assets/clock.png'),
    RaagaCardNew:require('../assets/Raaga_card_new.png'),
    GreenTrends:require('../assets/greenTrends.png'),
    EditOrange:require('../assets/edit-orange.png'),
    Routing:require('../assets/routing.png'),
    ClockGrey:require('../assets/clock-grey.png'),
    NoteEdit:require('../assets/note-edit.png'),
    Pin:require('../assets/pin.png'),
    UnPin:require('../assets/unPin.png'),
    DecisionMakerStar:require("../assets/decisionMaker_star.png"),
    MenuBoard:require('../assets/menu-board.png'),
    StarOutline:require("../assets/star-outline.png"),
    WireLogo:require('../assets/wirelogo.png'),
    EditBlue:require('../assets/edit-blue.png'),
    HomeNew: require("../assets/Home_new.png"),
    CalendarNew:require("../assets/calendar_new.png"),
    BoxNew:require("../assets/box_new.png"),
    MenuIconPersonNew:require("../assets/Menu_icon_person_new.png")

    // NotificationIcon: require('../assets/notification.png'),
    // New_NotificationIcon: require('../assets/newNotification.png'),
}

export default Images;