const Languages = {
  //pdf view
  DocmentViewer: 'Document Viewer',
  Share: 'Share',
  DownloadPDF: 'Download PDF',
  StoragePermission: 'Storage permission is required to download the file',
  PermissionDenied: 'Permission Denied',
  SharePDF: 'Share PDF',
  DownloadComplete: 'Download completed. Please check your download folder.',
  ErrorFetching: 'Error fetching File type',
  ErrorLoadPage: 'Error loading page',
  FailedDownload: 'Failed to download file',
  Error: 'Error',
  //login
  VerifyOTP: 'Verify OTP',
  SendOTP: 'Send OTP',
  Register:'Register',
  DontReceiveOTP: "Didn't Receive OTP?",
  EnterMobiNo: 'Enter your mobile number',
  OTP: 'OTP',
  Login: 'Log in',
  EnterMobiOTPToVerify: 'Enter your Mobile Number and OTP to verify',
  MobileNo: 'Mobile Number',
  OTPSentSuccess: 'Otp sent successfully',
  InvalidOTP: 'Invalid OTP',
  Resend: 'Resend',
  Please_check_your_internet_connection:' Please check your internet connection',
  //Home
  NoDataAvailable: 'No data available',
  GeolocationPermission: 'Geolocation Permission',
  AccessLocation: 'Can we access your location?',
  AskMeLater: 'Ask Me Later',
  Cancel: 'Cancel',
  Ok: 'Ok',
  PermissionDenied: 'Permission Denied',
  Granted: 'granted',
  AcceptInvite: 'Invite Accepted successfully',
  InviteDeclined: 'Invite Declined successfully',

  //Action screen
  FeedbackSubmitted: 'Feedback has been successfully submitted',
  You_have_been_geotagged_at_the_demo_client_place:
    'You have been geotagged at the demo client place',
  Confirm: 'Confirm',
  Theory_should_be_explained_before_procedure:
    'Theory should be explained before procedure',
  Share_Feedback_Link: 'Share Feedback Link',
  Check_Out: 'Check Out',
  Check_In: 'Check In',
  Proceed: 'Proceed',
  Service_and_product_detail: 'Service and product detail',
  Participants: 'Participants',
  Check_For_Response: 'Check For Response',
  Demo_Completed: 'Demo Completed',
  Please_fill_all_the_fields: 'Please fill all the fields',
  Please_fill_all_the_additional_products_details:
    'Please fill all the additional products details',
  Add_additional_service_products: 'Add additional service products',
  Please_fill_all_the_products: 'Please fill all the products',
  Services_should_not_be_empty: 'Services should not be empty',
  Please_fill_all_the_participants: 'Please fill all the participants',
  Please_select_participants: 'Please select participants',
  Please_fill_notes: 'Please fill notes',
  Alert: 'Alert',
  Feedback_is_not_yet_completed: 'Feedback is not yet completed',
  Feedback_sent_successfully: 'Feedback sent successfully',
  Grooming_Check: 'Grooming Check',
  Product_Picture: 'Product Picture',
  Client_Place_Picture: 'Client Place Picture',
  Theory_explained: 'Theory explained',
  Before_Picture_of_Model: 'Before Picture of Model',
  Steps_of_Procedure: 'Steps of Procedure',
  After_Picture_of_Model: 'After Picture of Model',
  Check_Out_successfully_done: 'Check Out successfully done',
  Check_In_successfully_done: 'Check In successfully done',
  Livewire_App_Camera_Permission: 'Livewire App Camera Permission',
  Livewire_App_needs_access_to_your_camera:
    'Livewire App needs access to your camera',
  Image_size_should_be_less_than_5MB: 'Image size should be less than 5 MB',
  Image_size_should_be_less_than_2MB: 'Image size should be less than 2 MB',
  Image_format_should_be_jpeg_or_png: 'Image format should be jpeg or png',
  Camera_Permission_Denied: 'Camera Permission Denied',
  Resend_Feedback: ' Resend Feedback',
  Notes: 'Notes',
  check_In_Instruction:
    'Make sure you are at the demo client place before check-In',
  check_Out_Instruction:
    'Make sure you are at the demo client place before check-Out',
  Step_One: 'Step 1',
  Step_12: 'Step 12',
  Please_select_product: 'Please select product',
  invalid_mobileNumber_error:
    'Invalid mobile number. Please enter a valid 10-digit Indian number starting with 7, 8, or 9.',
  Please_fill_participant_name: 'Please fill participant name',
  Please_fill_mobile_number_for_participant:
    'Please fill mobile number for participant',
  Please_select_Additional_product: 'Please select Additional product',
  Demo_ID: 'Demo ID',
  Client: 'Client',
 
  Mobile_Number: 'Mobile Number',
  Enter_Mobile_Number: 'Enter Mobile Number',
  Given_Service: 'Given Service',
  No_of_Products: 'No of Products',
  Select_product: 'Select product',
  Search: 'Search...',
  Demo_Capacity: 'Demo Capacity',
  Additional_Service_Provided: 'Additional Service Provided',
  Select_here: 'Select here',
  No_of_Participants: 'No of Participants',
  Role: 'Role',
  Enter_notes: 'Enter notes',
  file_Format_instruction:
    'Accepted file formats: JPEG (.jpg) & PNG (.png), Max size: 5MB.',
  Total_Picture_Uploaded: 'Total Picture Uploaded: ',
  Attach: 'Attach',
  Upload_Images: 'Upload Images',
  No: ' No ',
  Yes: 'Yes',
  Did_you_Explained_the_Theory: 'Did you Explain the Theory ?',
  You_are_here: 'You are here',
  Accepted_file_formats:
    ' Accepted file formats: JPEG (.jpg) & PNG (.png), Max size: 5MB.',

  //Basic detail
  Please_select_a_valid_date_of_birth: 'Please select a valid date of birth',
  Age_should_be_greater_than_18: 'Age should be greater than 18',
  Please_select_all_the_fields: 'Please select all the fields',
  Finish: 'Finish',
  Upload_Successfully: 'Upload Successfully',
  ASM: 'ASM',
  RSM: 'RSM',
  Please_fill_out_the_Basic_Details: ' Please fill out the Basic Details',
  Select_the_Brand_you_prefer: 'Select the Brand you prefer',
  Select_the_Location_Handled: 'Select the Location Handled',
  These_details_will_be_shown_to_your_salesman:
    'These details will be shown to your salesman',
  Select_all_that_applies: 'Select all that applies:',
  Mobile_No_is_required: 'Mobile Number is required',
  Mobile_is_not_valid: 'Mobile Number is not valid',
  First_Name: 'First Name',
  Enter_Name: 'Enter Name',
  First_name_is_required: 'First name is required',
  Last_Name: 'Last Name',
  Last_name_is_required: 'Last name is required',
  Only_Alphabets_are_Allowed: 'Only Alphabets are Allowed',
  Date_of_Birth: 'Date of Birth',
  Date_of_Birth_is_required: 'Date of Birth is required',
  Work_Experience: 'Work Experience',
  Enter_Experience: 'Enter Experience',
  Experience_is_required: 'Experience is required',
  Experience_is_not_valid: 'Experience is not valid',
  Gender: 'Gender',
  
  Select_Gender: 'Select Gender',

  Gender_Required: 'Gender is required',
  Address: 'Address',
  Enter_Address: 'Enter Address',
  Address_is_required: 'Address is required',
  Upload_Profile_Picture: ' Upload Profile Picture',
  Upload_Image: 'Upload Image',
  Select_Service_type_you_prefer: 'Select the Service type you prefer',
  Select_Service_category_you_prefer: 'Select the Service category you prefer',
  Select_State: 'Select State',
  City: 'City',
  Select_City: 'Select City',
  Salesman: 'Salesman',
  Next: 'Next',
  Update: 'Update',
  No_data_available: 'No data available',
  Loading: 'Loading...',
  years: 'years',
  State: 'State',
  RTETitle:'RTE',
  RTE:'select Rte',
  //ClientDemoHistory
  All: 'All',
  Date: 'Date',
  Brand: 'Brand',
  Service: 'Service',
  ServiceVarient: 'Service Variant',
  SaleDate:"Sale Date",
  
  //ClientList
  Clients: 'Clients',
  Pinned_Clients: 'Pinned Clients',
  Recent_Clients: 'Recent Clients',
  
  //Sales
  Sales_History: 'Sales History',
  Add_Sales: 'Add Sales',
  UpSell: ' Up-sell',
  CrossSell: 'Cross-sell',
  DirectSale: 'Direct-sale',
  Select_Demo: 'Select Demo',
  Product_Name: 'Product Name',
  Quantity_Sold: 'Quantity Sold',
  Enter_Quantity_Sold: 'Enter Quantity Sold',
  Quantity_Sold_is_required: 'Quantity Sold is required',
  Quantity_Sold_is_not_valid: 'Quantity Sold is not valid',
  Amount: 'Amount',
  Enter_Amount: 'Enter Amount',
  Amount_is_required: 'Amount is required',
  Amount_is_not_valid: 'Amount is not valid',
  Select: 'Select',

  //NotesScreen
  Add_Notes: ' Add Notes',
  Notes_is_required: 'Notes is required',
  Submit: 'Submit',

  //Demo Detail
  Do_you_want_to_Cancel_the_demo: 'Do you want to Cancel the demo ?',
  Enter_reason_here: 'Enter reason here',
  Close: 'Close',
  Cancel_Demo: 'Cancel Demo',
  Product_Images: 'Product_Images',
  Feedback_Shared: 'Feedback Shared',
  No_Demo_Details_to_View: 'No Demo Details to View',
  Demo_Cancelled_Successfully: 'Demo Cancelled Successfully',
  Reason_required: 'Reason is required',
  Trainer: 'Trainer',
  Attachment: 'Attachment',
  Status_Map: 'Status Map',
  Action: 'Action',
  Feedback_Details: 'Feedback Details',
  Feedback: 'Feedback',

  //DecisionMaker Feedback
  Question1: 'Was the trainer professional and knowledgeable?',
  Question2: 'Did the trainer explain the theory and procedure clearly?',
  Question3:
    'Were the benefits and usage of the products explained effectively?',
  Question4: 'Did the demo meet your initial expectations?',
  Question5: 'How well did the trainer address your questions and concerns?',
  Question6:
    'How would you rate the results of the products demonstrated on the Models?',
  Question7: 'How like are you to use the demonstrated products in your salon?',
  Question8:
    'Overall, how would you rate your experience with the product demo?',
  Question9: 'Overall,how would you rate your experience with our Trainer?',
  Feedback_Generation: 'Feedback Generation',
  Decision_Maker_Name: ' Decision Maker Name',
  Decision_Maker_Mobile_Number: 'Decision Maker Mobile Number',
  POC_Name: 'POC Name',
  POC_Mobile_Number: 'POC Mobile Number',

  //GetStart
  Welcome_To_Raaga: 'Welcome To Raaga',
  Locations_handled: 'Locations handled',
  Preferred_Location: 'Preferred Location',
  ServicesType: 'ServicesType',
  ServiceCategory: 'Service Category',
  Service_Type: 'Service type',
  You_can_also_change_these_details_on_your_Profile:
    'You can also change these details on your Profile',
  Lets_get_Started: 'Lets get Started',

  //Inventory Detail
  Requested_Date: 'Requested Date',
  Requested_Qty: 'Requested Qty',
  Approved_Date: 'Approved Date',
  Rejected_Date: 'Rejected Date',
  Search_Inventory: 'Search Inventory..',
  Products_Availed: 'Products Availed',
  Demos_Taken: 'Demos Taken',
  Consumption: 'Consumption',
  Balance: 'Balance',
  Request_History: 'Request History',
  Opening_Stock: 'Opening Stock',
  Products: 'Products',
  Stock_History: 'Stock History',
  Add_Product: 'Add Product',
  Add_Stock: 'Add Stock',
  Select_Product_Name: 'Select Product Name',
  Product_Name_required: 'Product Name is required',
  Mat_Code: 'Mat Code',
  Select_Mat_Code: 'Select Mat Code',
  Mat_Code_is_required: 'Mat Code is required',
  Quantity: 'Quantity',
  Enter_Quantity: 'Enter Quantity',
  Quantity_required: 'Quantity is required',
  Quantity_not_valid: 'Quantity is not valid',
  Quantity_in_Hand: 'Quantity in Hand',
  Basic_Quantity: 'Basic Quantity',
  Request_stock: 'Request a stock',
  Stock_request_instruction:
    'Stock request will be verified and approved by the admin',
  Quantity_Needed: 'Quantity Needed',
  Comments: 'Comments',
  Enter_comments: 'Enter comments',
  Comments_required: 'Comments is required',

  //Notifications
  Notifications: 'Notifications',

  //Profile
  CANCELLED: 'CANCELLED',
  Do_you_want_to_Logout: 'Do you want to Logout ?',
  Logout: 'Logout',
  One_Day_Before: '1 Day Before',
  four_Hrs_Before: '4 Hrs Before',
  Search_items: 'Search items',
  Save: 'Save',
  Declined: 'Declined',
  My_Profile: 'My Profile',
  Settings: 'Settings',
  Invite_History: 'Invite History',
  Demo_History: 'Demo History',
  Teams: 'Teams',
  Reports: 'Reports',
  Notification_Preferences: 'Notification Preferences',
  Demo_Acceptance: 'Demo Acceptance',
  Demo_Rejections: 'Demo Rejections',
  Demo_Reinvite_Accepted: 'Demo Reinvite Accepted',
  Demo_Reminder: 'Demo Reminder',
  Demo_Reinvite_Rejected: 'Demo Reinvite Rejected',
  Demo_Invite_Received: 'Demo Invite Received',
  Demo_Reinvite_Received: 'Demo Reinvite Received',
  Evaluation_Blocked: 'Evaluation Blocked',
  Evaluation_Rejected: 'Evaluation Rejected',
  Evaluation_Approved: 'Evaluation Approved',
  Demo_Cancelled: 'Demo Cancelled',

  //Sales Report
  Sales_Report: 'Sales Report',
  Invite_withdrawn_successfully: 'Invite withdrawn successfully',
  Invite_sent_successfully: 'Invite sent successfully',
  Resend_Invite: ' Resend Invite',
  Withdraw_Invite: 'Withdraw Invite',

  //SceduleDemo
  Please_fill_all_the_mandatory_fields: 'Please fill all the mandatory fields',
  Schedule_a_Demo: 'Schedule a Demo',
  Client_Name: 'Client Name',
  Select_Client_Name: 'Select Client Name',
  Client_Name_is_required: 'Client Name is required',
  Saloon_Code: 'Saloon Code',
  Select_Code: 'Select Code',
  Saloon_Code_is_required: 'Saloon Code is required',
  Location: 'Location',
  Decision_Maker: 'Decision Maker',
  Decision_Maker_is_required: 'Decision Maker is required',
  Time: 'Time',
  Time_required: 'Time is required',
  Brand_is_required: 'Brand is required',
  Service_Type: 'Service Type',
  Service_Type_is_required: 'Service Type is required',
  Service_category_is_required: 'Service category is required',
  Service_is_required: 'Service is required',
  SOP_Attachment: 'SOP Attachment',
  SOP: 'SOP',
  Grooming_Pdf_Attachment: ' Grooming Pdf Attachment',
  Grooming: 'Grooming',
  Check_Available_Trainers: 'Check Available Trainers',
  No_Demos_Scheduled_Today: 'No Demos Scheduled Today',
  Set_your_Calendar: 'Set your Calendar',
  Working_Day: ' Working Day',
  Leave: 'Leave',
  Week_Off: 'Week Off',
  Holiday: 'Holiday',
  Evaluation_Pending: 'Evaluation Pending',
  Send_Request: 'Send Request',
  Set: 'Set',
  Accept_Invite_Pending: ' Accept Invite Pending',
  Send_Invite: 'Send Invite',
  Schedule: 'Schedule',
  Search_for_Trainers: 'Search for Trainers',
  Cancelled: 'Cancelled',

  Email:'Email ID',
  EmailID:'Enter the EmailID',
  Email_Required:'EmailId is required',
  Invalid_email:'Invalid EmailId',
  Name: 'Name',
  User_Type:'User Type',
  Select_UserType: 'Select Name',
  Select_UserRule: 'Name is required',
  Enter_Name: 'Enter Name',
  Name_is_required: 'Name is required',
  
};

export default Languages;
