// export const BASE_URL=`https://gateway.thelivewire.in`;//Prod BaseUrl
export const BASE_URL=`https://livewire-qa-gateway.citpl.info`;//QA BaseUrl
//export const BASE_URL=`https://livewire-dev-gateway.citpl.info`;//Dev BaseUrl
export const SEND_OTP=`/auth/auth/sendOtp?`;
export const VERIFY_OTP=`/auth/auth/verifyOtp?`;
export const RESEND_OTP=`/auth/auth/resendOtp?`;
export const REFRESH=`/auth/auth/refreshToken`;
export const REGISTER=`/auth/api/register`;
export const USER_UPDATE=`/sales/user/update`;
export const UPCOMING_LIST=`/demo/demo/upcomingList`;
export const CLIENT_LIST=`/demo/client/getAllClientList`;
export const GET_ALL_BRANDS=`/sales/master/getAllBrand`;
export const SERVICE_TYPE_LIST=`/sales/master/getAllService/byServiceType?`;
export const GET_CITY_BY_STATE=`/sales/master/getCityListByState?`;
export const GET_ALL_STATE=`/sales/master/getAllState`;
export const SALES_MAN_LIST=`/sales/master/getSalesmanListByLocation?`;
export const GET_ALL_PENDING=`/sales/invite/getAllPending`;
// export const PRODUCT_LIST=`/demo/demo/productsList`;
export const BRAND_LIST=`/demo/demo/brandsList`;
export const DEMO_SERVICE_TYPE_LIST=`/sales/master/getAllServiceType`;
export const GET_ALL_SERVICE_BY_ID=`/sales/master/getAllService/byServiceType?`;
export const DEMO_CREATE=`/demo/demo/create`;
export const CLIENT_LOCATIONS=`/demo/client/clientLocations?`;
export const WEEKLY_LIST=`/demo/demo/weeklyList?`;
export const USER_PROFILE=`/sales/user/trainer/getById?`;
export const DEMO_HISTORY=`/demo/demo/getHistory?`;
export const DECLINED_DEMO=`/demo/demo/getById?`;
export const OPEN_STOCK='/sales/trainersInventory/getProductsList/ByUserId?';
export const GET_AVAILABLE_TRAINER=`/sales/invite/getAvailTrainers?`;
export const TRAINER_GETbY_ID=`/sales/user/trainer/getById?`;
export const GETALL_FOR_MONTH_YEAR = `/sales/calendar/getAllForMonthYear?`
export const CALENDAR_MARK = `/sales/calendar/mark`
export const SEND_INVITE=`/sales/invite/send`;
export const AUDIT_UPDATE=`/demo/demo/audit/update`;
export const DEMO_GET_BY_ID=`/demo/demo/getById?`;
export const INVITE_ACCEPT=`/sales/invite/accept`;
export const INVITE_DECLINE=`/sales/invite/decline`;
export const PROFILE_PIC=`/sales/user/save/profile`;
export const DEMO_CANCEL=`/demo/demo/cancel`;
export const INVITE_RESEND=`/sales/invite/resend?`;
export const INVITE_WITHDRAW=`/sales/invite/withdraw?`;
export const WEATHER=`/sales/weather?`;
export const SETTING_UPDATE=`/sales/user/userSetting/update`;
export const GET_USER_SETTING=`/sales/user/userSetting/getByUserId?`;
export const GET_ALL_NOTIFICATION=`/demo/getAllNotification`;
export const IN_ACTIVE_NOTIFICATION=`/demo/inActiveNotification`;
export const POLL_FEEDBACK=`/demo/demo/pollFeedback?`;
export const GET_DOCUMENTS=`/demo/demo/getDemoDocuments`;
export const LOG_OUT=`/auth/auth/logout?`;
export const INVITE_HISTORY=`/sales/invite/getAllHistory`;
export const ALL_CLIENTLIST = `/demo/client/clientsList`;
export const PRODUCT_LIST=`/demo/demo/productsList`;
export const DEMO_PRODUCT_LIST=`/demo/demo/trainersProductsList`;
export const FEEDBACK_DETAIL=`/demo/feedback/getByDemoId?`;
export const PINNED_LIST=`/demo/client/pinnedList`;
export const SEARCH_LIST=`/demo/client/fetchAll?`;
export const RECENT_LIST=`/demo/client/recentList`;
export const DEMO_CLIENT=`/demo/client/getById?`;
export const TOGGLE_PIN=`/demo/client/togglePin?`;
export const CLIENT_DEMO_HISTORY=`/demo/demo/getHistory?`;
export const CLIENT_SALES_HISTORY=`/demo/client/getSales/forSalesmanAndClientById?`;
export const SALES_SAVE=`/demo/client/sales`;
export const NOTES_SAVE=`/demo/client/notes`;
export const SALES_DEMO_ID_LIST=`/demo/client/getDemosForsalesman`;
export const NOTES_LIST=`/demo/client/getNotes/forSalesmanAndClientById?`;
export const PROFILE_SALES_HISTORY=`/demo/client/getSales/forSalesman`;
export const RSM_SALES=`/demo/client/getsales/rsm`;
export const ASM_SALES=`/demo/client/getsales/asm`;
export const ASM_LIST=`/sales/team/getAllAsm/byRSM`;
export const ASM_SALESMAN_LIST=`/sales/team/getAllSalesman/byASM`;
export const RSM_SALESMAN_LIST=`/sales/team/getAllSalesman/byRSM`;
export const RSM_TRAINER_LIST=`/sales/team/getAllTrainer/byRSM`;
export const ASM_TRAINER_LIST=`/sales/team/getAllTrainer/byASM`;
export const GETAllASM=`/sales/team/getAllASMBySalesman`;
export const GETAllRSM=`/sales/team/getAllRSMBySalesman`;
export const INVENTORY_SEARCH=`/sales/trainersInventory/inventorySearch`;
export const STOCK_LIST=`/sales/trainersInventory/stockHistory`;
export const PRODUCT_REQUEST=`/sales/trainersInventory/request`;
export const GET_QTY_IN_HAND=`/sales/trainersInventory/getQtyInHand`;
export const STOCK_UPDATE=`/sales/trainersInventory/stockUpdate`;
export const SALES_CONVERSION_BRAND=`/demo/reports/salesConversionByBrand?`;
export const SALES_CONVERSION_TRAINER=`/demo/reports/salesConversionByUser?`;
export const DEMO_ASSIGNMENT_BRAND=`/demo/reports/salesman/demoAssignedByBrand?`;
export const SALES_REPORT_BRAND=`/demo/reports/salesReportByBrand?`;
export const TOP_SELLING_PRODUCT=`/demo/reports/topSellingProduct?`;
export const TOP_SELLING_BRAND=`/demo/reports/topSellingBrand?`;
export const DEMO_COUNT_BRAND=`/demo/reports/trainer/demoCount/brand?`;
export const WEEKLY_DEMO_REPORT=`/demo/reports/trainer/demoCount/service?`;
export const DEMO_FEEDBACK_REPORT= `/demo/reports/feedbackReport?`;
export const TRAINER_CALENDAR_REPORT=`/demo/reports/trainerCalendar?`;
export const TOTAL_DEMO_COUNT= `/demo/reports/trainer/demo/stats?`;
export const DEMO_STATUS_REPORT= '/demo/reports/trainer/overall/stats?';
export const GET_ALL_TRAINER=`/demo/reports/getAllTrainer/salesman`;
export const COMPLETED_DROPPED=`/demo/reports/completedAndDropped?`;
export const TOP_SALES_RECORD=`/demo/reports/topSalesRecord?`;
export const GET_ALL_TRAINER_RSM=`/demo/reports/getAllTrainer/rsm`;
export const GET_ALL_ASM=`/demo/reports/getAllASM/rsm`;
export const GET_SERVICE_TYPE=`/demo/demo/service-types`
export const ADDITIONAL_SERVICES=`/demo/demo/services`;
export const SALES_SERVICE_TYPES=`/sales/user/service-types`;

//getVersion
export const GET_VERSION=`https://mosaic-dev-backend.citpl.info/version/getVersion?`
export const SAVE_APP_DOWNLOADS=`https://mosaic-dev-backend.citpl.info/version/saveAppDownloadDetails`
